# Generated by Django 3.0 on 2019-12-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='norms',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='western',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
                ('normsPred', models.IntegerField()),
                ('actualDem', models.IntegerField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.norms')),
            ],
        ),
        migrations.CreateModel(
            name='island',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
                ('normsPred', models.IntegerField()),
                ('actualDem', models.IntegerField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.norms')),
            ],
        ),
        migrations.CreateModel(
            name='eastern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
                ('normsPred', models.IntegerField()),
                ('actualDem', models.IntegerField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.norms')),
            ],
        ),
    ]
