# Generated by Django 3.0 on 2019-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('island', models.IntegerField()),
                ('western', models.IntegerField()),
                ('eastern', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
