# Generated by Django 3.0 on 2020-01-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0002_predict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eastern',
            old_name='high',
            new_name='population',
        ),
        migrations.RenameField(
            model_name='island',
            old_name='high',
            new_name='population',
        ),
        migrations.RenameField(
            model_name='western',
            old_name='high',
            new_name='population',
        ),
        migrations.RemoveField(
            model_name='eastern',
            name='low',
        ),
        migrations.RemoveField(
            model_name='island',
            name='low',
        ),
        migrations.RemoveField(
            model_name='western',
            name='low',
        ),
    ]
